import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { ArrowUpRight, Plus, Search, UserRound, X } from 'lucide-react';
import { getListCustomersQueryKey, useCreateCustomer, useListCustomers } from '@workspace/api-client-react';
import { initials } from '@/lib/format';
import { EmptyState, LoadingBlock, QueryError, LoadingButton, SectionTitle } from '@/components/primitives';

export default function CustomersPage() {
  const [search, setSearch] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name: '', whatsapp: '', email: '', address: '' });
  const query = useListCustomers({ query: { queryKey: getListCustomersQueryKey() } });
  const create = useCreateCustomer();
  const customers = useMemo(() => (query.data ?? []).filter((customer) => `${customer.name} ${customer.whatsapp} ${customer.email ?? ''}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); create.mutate({ data: form }, { onSuccess: () => { setForm({ name: '', whatsapp: '', email: '', address: '' }); setShowForm(false); query.refetch(); } }); };
  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">People / customer file</p><h2 className="text-3xl font-extrabold tracking-[-.06em]">Customers</h2><p className="mt-2 text-sm text-muted-foreground">A clear history makes the next handoff faster.</p></div><button className="btn-primary self-start sm:self-auto" onClick={() => setShowForm((value) => !value)} data-testid="button-add-customer"><Plus className="size-4" /> Add customer</button></div>
      {showForm && <form onSubmit={submit} className="panel appear rounded-xl p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow mb-1">Customer intake</p><h3 className="text-sm font-extrabold">Create customer profile</h3></div><button type="button" className="btn-ghost" onClick={() => setShowForm(false)} data-testid="button-close-customer-form"><X className="size-4" /></button></div><div className="grid gap-4 md:grid-cols-4"><CustomerField label="Name" value={form.name} required onChange={(value) => setForm({ ...form, name: value })} testId="input-new-customer-name" /><CustomerField label="WhatsApp" value={form.whatsapp} required onChange={(value) => setForm({ ...form, whatsapp: value })} testId="input-new-customer-whatsapp" /><CustomerField label="Email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} testId="input-new-customer-email" /><CustomerField label="Address" value={form.address} onChange={(value) => setForm({ ...form, address: value })} testId="input-new-customer-address" /></div>{create.isError && <p className="mt-4 text-xs font-bold text-destructive">Could not create the customer. Try again.</p>}<div className="mt-5 flex justify-end"><button className="btn-primary" disabled={create.isPending} data-testid="button-submit-customer"><LoadingButton pending={create.isPending}>Save customer</LoadingButton></button></div></form>}
      <div className="panel rounded-xl p-3 md:p-4"><label className="relative block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="field pl-9" placeholder="Search customer name or WhatsApp" data-testid="input-customer-search" /></label></div>
      <SectionTitle eyebrow={`${customers.length} profiles`} title="Customer directory" detail="Open a profile to view repair history" />
      {query.isLoading ? <LoadingBlock lines={5} /> : query.isError ? <QueryError retry={() => query.refetch()} /> : customers.length === 0 ? <EmptyState title="No customers found" body="There are no profiles matching this search yet." action={<button className="btn-primary" onClick={() => setShowForm(true)} data-testid="button-empty-add-customer"><Plus className="size-4" /> Add first customer</button>} /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{customers.map((customer) => <div key={customer.id} className="panel group rounded-xl p-5 transition-transform hover:-translate-y-0.5" data-testid={`card-customer-${customer.id}`}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-secondary font-mono text-xs font-medium text-primary">{initials(customer.name)}</span><div><h3 className="text-sm font-extrabold">{customer.name}</h3><p className="mt-1 font-mono text-[10px] text-muted-foreground">{customer.whatsapp}</p></div></div><UserRound className="size-4 text-muted-foreground" /></div><div className="mt-6 grid grid-cols-2 gap-2 border-t border-border pt-4"><div><p className="font-mono text-[10px] uppercase text-muted-foreground">All repairs</p><p className="mt-1 text-lg font-extrabold">{customer.totalTickets}</p></div><div><p className="font-mono text-[10px] uppercase text-muted-foreground">Active now</p><p className="mt-1 text-lg font-extrabold text-primary">{customer.activeTickets}</p></div></div><Link href={`/tickets?search=${encodeURIComponent(customer.name)}`} className="btn-ghost mt-4 w-full justify-between border border-border/70" data-testid={`link-customer-history-${customer.id}`}>View repair history <ArrowUpRight className="size-4" /></Link></div>)}</div>}
    </div>
  );
}

function CustomerField({ label, value, onChange, required, testId }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; testId: string }) {
  return <label className="block"><span className="label">{label}{required && <span className="text-destructive"> *</span>}</span><input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="field" data-testid={testId} /></label>;
}