import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Link, useLocation, useParams } from 'wouter';
import { AlertCircle, ArrowLeft, Bell, Check, CreditCard, FileText, History, MessageSquare, Printer, RefreshCw, Save, Smartphone, UserRound, Wallet, Wrench } from 'lucide-react';
import { getGetTicketQueryKey, useGetTicket, useRecordPayment, useRetryNotification, useUpdateTicket, useUpdateTicketStatus } from '@workspace/api-client-react';
import { dateLabel, formatStatus, money, statusClass } from '@/lib/format';
import { LoadingBlock, LoadingButton, QueryError, SectionTitle } from '@/components/primitives';

const statuses = ['new', 'diagnosing', 'awaiting_parts', 'repairing', 'ready', 'completed', 'delayed'];

export default function TicketDetailPage() {
  const params = useParams<{ id?: string }>();
  const id = params.id ?? '';
  const [, setLocation] = useLocation();
  const client = useQueryClient();
  const query = useGetTicket(id, { query: { enabled: Boolean(id), queryKey: getGetTicketQueryKey(id) } });
  const updateTicket = useUpdateTicket();
  const updateStatus = useUpdateTicketStatus();
  const recordPayment = useRecordPayment();
  const retryNotification = useRetryNotification();
  const [edit, setEdit] = useState({ priority: 'normal', estimatedCompletion: '', diagnosis: '', cause: '', recommendation: '', laborCost: '0', partsCost: '0', delayReason: '', notes: '' });
  const [payment, setPayment] = useState({ amount: '', method: 'cash' });
  const [status, setStatus] = useState('');
  const [statusNote, setStatusNote] = useState('');

  useEffect(() => {
    if (query.data) {
      const ticket = query.data;
      setEdit({ priority: ticket.priority, estimatedCompletion: ticket.estimatedCompletion?.slice(0, 16) ?? '', diagnosis: ticket.diagnosis ?? '', cause: ticket.cause ?? '', recommendation: ticket.recommendation ?? '', laborCost: String(ticket.laborCost ?? 0), partsCost: String(ticket.partsCost ?? 0), delayReason: '', notes: '' });
      setStatus(ticket.status);
    }
  }, [query.data]);

  if (query.isLoading) return <div className="space-y-5"><div className="h-8 w-40 animate-pulse rounded bg-muted" /><LoadingBlock lines={7} /></div>;
  if (query.isError || !query.data) return <QueryError message="This ticket could not be opened." retry={() => query.refetch()} />;
  const ticket = query.data;
  const save = (event: React.FormEvent) => {
    event.preventDefault();
    updateTicket.mutate({ id, data: { ...edit, laborCost: Number(edit.laborCost) || 0, partsCost: Number(edit.partsCost) || 0 } }, { onSuccess: (next) => client.setQueryData(getGetTicketQueryKey(id), next) });
  };
  const changeStatus = () => updateStatus.mutate({ id, data: { status, note: statusNote || undefined, delayReason: edit.delayReason || undefined } }, { onSuccess: (next) => { client.setQueryData(getGetTicketQueryKey(id), next); setStatusNote(''); } });
  const addPayment = (event: React.FormEvent) => { event.preventDefault(); recordPayment.mutate({ id, data: { amount: Number(payment.amount) || 0, method: payment.method } }, { onSuccess: () => { setPayment({ amount: '', method: 'cash' }); query.refetch(); } }); };
  const failedNotifications = ticket.notifications?.filter((item) => item.status.toLowerCase() === 'failed') ?? [];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/tickets" className="btn-ghost" data-testid="link-back-ticket-list"><ArrowLeft className="size-4" /> Tickets</Link><span className="text-border">/</span><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{ticket.ticketNumber}</span></div><div className="flex gap-2"><button className="btn-secondary" onClick={() => window.print()} data-testid="button-print-receipt"><Printer className="size-4" /> Receipt</button><button className="btn-primary" onClick={() => document.getElementById('status-panel')?.scrollIntoView({ behavior: 'smooth' })} data-testid="button-change-status"><Wrench className="size-4" /> Update status</button></div></div>
      <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow mb-2">Service record / {ticket.ticketNumber}</p><h2 className="text-3xl font-extrabold tracking-[-.06em]">{ticket.deviceBrand} {ticket.deviceModel}</h2><div className="mt-3 flex flex-wrap items-center gap-3"><span className={statusClass(ticket.status)} data-testid="status-ticket-detail"><span className="status-dot bg-current" />{formatStatus(ticket.status)}</span><span className="font-mono text-[10px] text-muted-foreground">Intake {dateLabel(ticket.intakeDate)}</span>{ticket.priority === 'high' && <span className="font-mono text-[10px] font-medium uppercase text-destructive">High priority</span>}</div></div><div className="flex items-center gap-3"><div className="text-right"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Outstanding</p><p className={`text-2xl font-extrabold tracking-tight ${ticket.outstandingBalance > 0 ? 'text-destructive' : 'text-primary'}`} data-testid="text-outstanding-balance">{money(ticket.outstandingBalance)}</p></div><div className="size-12 rounded-xl bg-secondary p-3 text-primary"><Smartphone className="size-6" /></div></div></div>

      <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
        <div className="space-y-6">
          <section className="panel rounded-xl p-5 md:p-7"><SectionTitle eyebrow="Handoff" title="Device & customer" detail="What arrived at the counter" /><div className="grid gap-4 sm:grid-cols-2"><Info label="Customer" value={ticket.customerName} icon={UserRound} /><Info label="WhatsApp" value={ticket.whatsapp} icon={MessageSquare} /><Info label="Device" value={`${ticket.deviceBrand} ${ticket.deviceModel}`} icon={Smartphone} /><Info label="IMEI / serial" value={ticket.imei ?? 'Not recorded'} icon={FileText} /><Info label="Color" value={ticket.color ?? 'Not recorded'} icon={Smartphone} /><Info label="Complaint" value={ticket.complaint} icon={AlertCircle} /></div><div className="mt-5 grid gap-4 border-t border-border pt-5 sm:grid-cols-2"><div><p className="label">Condition</p><p className="text-xs leading-5">{ticket.condition ?? 'Not recorded'}</p></div><div><p className="label">Accessories</p><p className="text-xs leading-5">{ticket.accessories?.length ? ticket.accessories.join(', ') : 'None recorded'}</p></div></div></section>
          <form onSubmit={save} className="panel rounded-xl p-5 md:p-7"><SectionTitle eyebrow="Bench notes" title="Diagnosis & pricing" detail="Update the service plan as the repair reveals more" action={<button type="submit" className="btn-primary" disabled={updateTicket.isPending} data-testid="button-save-ticket"><LoadingButton pending={updateTicket.isPending}><Save className="size-4" /> Save</LoadingButton></button>} /><div className="grid gap-4 sm:grid-cols-2"><EditField label="Diagnosis" value={edit.diagnosis} onChange={(value) => setEdit({ ...edit, diagnosis: value })} testId="textarea-diagnosis" textarea /><EditField label="Cause" value={edit.cause} onChange={(value) => setEdit({ ...edit, cause: value })} testId="textarea-cause" textarea /><EditField label="Recommendation" value={edit.recommendation} onChange={(value) => setEdit({ ...edit, recommendation: value })} testId="textarea-recommendation" textarea /><EditField label="Delay reason" value={edit.delayReason} onChange={(value) => setEdit({ ...edit, delayReason: value })} testId="textarea-delay-reason" textarea /></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><EditField label="Labor cost" value={edit.laborCost} onChange={(value) => setEdit({ ...edit, laborCost: value })} testId="input-labor-cost" type="number" /><EditField label="Parts cost" value={edit.partsCost} onChange={(value) => setEdit({ ...edit, partsCost: value })} testId="input-parts-cost" type="number" /><EditField label="Estimate" value={edit.estimatedCompletion} onChange={(value) => setEdit({ ...edit, estimatedCompletion: value })} testId="input-detail-estimate" type="datetime-local" /></div>{updateTicket.isError && <p className="mt-4 text-xs font-bold text-destructive">Could not save these notes.</p>}</form>
          <section id="status-panel" className="panel rounded-xl p-5 md:p-7"><SectionTitle eyebrow="Workflow" title="Move the ticket" detail="Every status change creates a service history event" /><div className="grid gap-2 sm:grid-cols-4">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded-lg border px-3 py-3 text-left transition-colors ${status === item ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:bg-muted/55'}`} data-testid={`button-status-${item}`}><span className="block font-mono text-[10px] uppercase">{formatStatus(item)}</span>{status === item && <Check className="mt-2 size-4" />}</button>)}</div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={statusNote} onChange={(event) => setStatusNote(event.target.value)} className="field" placeholder="Optional note for the customer history" data-testid="input-status-note" /><button className="btn-primary sm:shrink-0" onClick={changeStatus} disabled={updateStatus.isPending || status === ticket.status && !statusNote} data-testid="button-save-status"><LoadingButton pending={updateStatus.isPending}>Apply status</LoadingButton></button></div></section>
        </div>
        <div className="space-y-6">
          <section className="panel rounded-xl p-5 md:p-6"><SectionTitle eyebrow="Payment desk" title="Balance & payments" detail={`${money(ticket.totalCost)} total repair value`} /><div className="mb-5 flex items-center justify-between rounded-lg bg-muted/55 p-4"><div><p className="font-mono text-[10px] uppercase text-muted-foreground">Paid</p><p className="mt-1 text-xl font-extrabold text-primary">{money(ticket.paidAmount)}</p></div><Wallet className="size-5 text-primary" /><div className="text-right"><p className="font-mono text-[10px] uppercase text-muted-foreground">Due</p><p className="mt-1 text-xl font-extrabold text-destructive">{money(ticket.outstandingBalance)}</p></div></div><form onSubmit={addPayment} className="space-y-3 border-b border-border pb-5"><div className="grid grid-cols-2 gap-2"><label><span className="label">Amount</span><input className="field" type="number" min="0" step="0.01" required value={payment.amount} onChange={(event) => setPayment({ ...payment, amount: event.target.value })} placeholder="0.00" data-testid="input-payment-amount" /></label><label><span className="label">Method</span><select className="field" value={payment.method} onChange={(event) => setPayment({ ...payment, method: event.target.value })} data-testid="select-payment-method"><option value="cash">Cash</option><option value="card">Card</option><option value="transfer">Transfer</option></select></label></div><button className="btn-secondary w-full" disabled={recordPayment.isPending} data-testid="button-record-payment"><LoadingButton pending={recordPayment.isPending}><CreditCard className="size-4" /> Record payment</LoadingButton></button></form>{ticket.payments?.length ? <div className="mt-4 space-y-3">{ticket.payments.map((item) => <div key={item.id} className="flex items-center justify-between"><div><p className="text-xs font-bold">{item.method}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{dateLabel(item.paidAt, true)}</p></div><p className="font-mono text-xs font-medium text-primary">{money(item.amount)}</p></div>)}</div> : <p className="mt-4 text-xs text-muted-foreground">No payments recorded yet.</p>}</section>
          <section className="panel rounded-xl p-5 md:p-6"><SectionTitle eyebrow="Customer messages" title="WhatsApp notifications" detail="Delivery status from the service desk" action={<Bell className="size-4 text-primary" />} />{failedNotifications.length > 0 && <div className="mb-4 rounded-lg border border-destructive/20 bg-destructive/5 p-3"><p className="text-xs font-bold text-destructive">{failedNotifications.length} notification failed</p>{failedNotifications.map((item) => <button key={item.id} className="btn-ghost mt-2 px-0 text-destructive" onClick={() => retryNotification.mutate({ id, notificationId: item.id }, { onSuccess: () => query.refetch() })} data-testid={`button-retry-notification-${item.id}`}><RefreshCw className="size-3.5" /> Retry delivery</button>)}</div>}{ticket.notifications?.length ? <div className="space-y-4">{ticket.notifications.map((item) => <div key={item.id} className="flex gap-3" data-testid={`row-notification-${item.id}`}><span className={`mt-1 size-2 rounded-full ${item.status.toLowerCase() === 'sent' ? 'bg-primary' : item.status.toLowerCase() === 'failed' ? 'bg-destructive' : 'bg-accent'}`} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold">{item.type}</p><span className="font-mono text-[10px] uppercase text-muted-foreground">{item.status}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.message}</p></div></div>)}</div> : <p className="text-xs text-muted-foreground">No messages have been sent.</p>}</section>
          <section className="panel rounded-xl p-5 md:p-6"><SectionTitle eyebrow="Audit trail" title="Status history" detail="A record of every handoff" action={<History className="size-4 text-primary" />} /><div className="space-y-4">{ticket.history?.map((item) => <div key={item.id} className="flex gap-3" data-testid={`row-history-${item.id}`}><span className="mt-1.5 size-2 rounded-full bg-primary" /><div><p className="text-xs font-bold">{formatStatus(item.status)}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{dateLabel(item.at, true)} · {item.actor}</p>{item.note && <p className="mt-1 text-xs text-muted-foreground">{item.note}</p>}</div></div>)}</div></section>
        </div>
      </div>
    </div>
  );
}

function Info({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: string }) { return <div className="rounded-lg bg-muted/50 p-3"><div className="flex items-center gap-2 text-primary"><Icon className="size-3.5" /><p className="label mb-0">{label}</p></div><p className="mt-2 text-xs font-bold leading-5">{value}</p></div>; }
function EditField({ label, value, onChange, testId, textarea, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; testId: string; textarea?: boolean; type?: string }) { return <label className="block"><span className="label">{label}</span>{textarea ? <textarea value={value} onChange={(event) => onChange(event.target.value)} className="field min-h-24 resize-y" data-testid={testId} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="field" data-testid={testId} />}</label>; }