import { useState } from 'react';
import { useParams, useLocation, Link } from 'wouter';
import { ArrowLeft, Check, Clock3, MapPin, Search, Smartphone } from 'lucide-react';
import { getGetPublicTrackingQueryKey, useGetPublicTracking } from '@workspace/api-client-react';
import { dateLabel, formatStatus, statusClass } from '@/lib/format';
import { LoadingBlock, QueryError } from '@/components/primitives';

export default function TrackingPage() {
  const params = useParams<{ ticketNumber?: string }>();
  const [, setLocation] = useLocation();
  const [lookup, setLookup] = useState(params.ticketNumber === 'lookup' ? '' : params.ticketNumber ?? '');
  const number = params.ticketNumber && params.ticketNumber !== 'lookup' ? params.ticketNumber : '';
  const query = useGetPublicTracking(number, { query: { enabled: Boolean(number), queryKey: getGetPublicTrackingQueryKey(number) } });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (lookup.trim()) setLocation(`/track/${lookup.trim()}`); };
  if (!number) return <div className="mx-auto max-w-xl py-10 md:py-20"><Link href="/" className="btn-ghost mb-12" data-testid="link-track-back"><ArrowLeft className="size-4" /> Back to station</Link><div className="panel overflow-hidden rounded-2xl"><div className="bg-sidebar p-7 text-sidebar-foreground md:p-10"><p className="eyebrow text-sidebar-primary">Customer portal</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.06em]">Where’s your phone?</h2><p className="mt-3 text-sm leading-6 text-sidebar-foreground/60">Enter the ticket number from your service receipt to see the latest repair status.</p></div><form onSubmit={submit} className="p-7 md:p-10"><label className="label" htmlFor="tracking-number">Ticket number</label><div className="flex gap-2"><input id="tracking-number" value={lookup} onChange={(event) => setLookup(event.target.value)} className="field" placeholder="ET-1048" required data-testid="input-tracking-number" /><button className="btn-primary" data-testid="button-track"><Search className="size-4" /> Track</button></div></form></div></div>;
  if (query.isLoading) return <div className="mx-auto max-w-3xl py-12"><LoadingBlock lines={5} /></div>;
  if (query.isError || !query.data) return <div className="mx-auto max-w-3xl py-12"><QueryError message="We couldn’t find that ticket. Check the number on your receipt." retry={() => query.refetch()} /><Link href="/track/lookup" className="btn-secondary mt-4" data-testid="link-try-another">Try another number</Link></div>;
  const ticket = query.data;
  return <div className="mx-auto max-w-3xl space-y-6 py-4 md:py-10"><div className="flex items-center justify-between"><Link href="/track/lookup" className="btn-ghost" data-testid="link-track-another"><ArrowLeft className="size-4" /> Track another</Link><span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-primary"><span className="status-dot bg-primary" /> Live service record</span></div><div className="panel overflow-hidden rounded-2xl"><div className="bg-sidebar p-7 text-sidebar-foreground md:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs text-sidebar-primary">{ticket.ticketNumber}</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.06em]">{ticket.deviceBrand} {ticket.deviceModel}</h2><p className="mt-2 text-sm text-sidebar-foreground/60">Hello, {ticket.customerName}</p></div><span className={`${statusClass(ticket.status)} bg-sidebar-accent text-sidebar-foreground`} data-testid="status-public-ticket"><span className="status-dot bg-sidebar-primary" />{formatStatus(ticket.status)}</span></div></div><div className="p-7 md:p-10"><div className="grid gap-4 sm:grid-cols-3"><Info icon={Smartphone} label="Reported issue" value={ticket.complaint} /><Info icon={Clock3} label="Estimated completion" value={dateLabel(ticket.estimatedCompletion)} /><Info icon={MapPin} label="Pickup" value={ticket.pickupInfo ?? 'We’ll share pickup details when ready'} /></div>{ticket.delayReason && <div className="mt-6 rounded-lg border border-destructive/25 bg-destructive/5 p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-destructive">Schedule note</p><p className="mt-2 text-sm font-bold">{ticket.delayReason}</p></div>}<div className="mt-9"><p className="eyebrow mb-4">Service timeline</p><div className="space-y-0">{ticket.history?.map((event, index) => <div key={event.id} className="relative flex gap-4 pb-6 last:pb-0" data-testid={`row-public-history-${event.id}`}><div className="relative flex w-4 justify-center"><span className={`z-1 mt-1.5 size-3 rounded-full border-2 ${index === 0 ? 'border-primary bg-primary' : 'border-border bg-card'}`} />{index < ticket.history.length - 1 && <span className="absolute top-4 h-full w-px bg-border" />}</div><div><p className="text-xs font-extrabold">{formatStatus(event.status)}</p><p className="mt-1 text-[11px] text-muted-foreground">{dateLabel(event.at, true)} · {event.actor}</p>{event.note && <p className="mt-2 text-xs text-muted-foreground">{event.note}</p>}</div></div>)}</div></div></div></div><p className="text-center font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Questions? Contact the service desk on your receipt.</p></div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof Smartphone; label: string; value: string }) { return <div className="rounded-lg bg-muted/55 p-4"><Icon className="size-4 text-primary" /><p className="mt-4 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xs font-bold leading-5">{value}</p></div>; }